engines:
 rubocop:
   enabled: false
 duplication:
   enabled: true
 metrics:
   enabled: true
 coverage:
   enabled: false
exclude_paths:
  - src/ArduinoJson/**
  - src/PubSubClient/**
  - src/WiFiManager/**